// @ts-check
// Flat ESLint config (ESLint v9+ / v10).
//
// Layering order matters:
//   1. Ignores (what ESLint never touches)
//   2. typescript-eslint recommended — applied to all TS/TSX repo-wide
//   3. eslint-config-next — scoped to web/ only (Next.js conventions)
//   4. eslint-config-prettier — LAST, so formatting is owned by Prettier alone
//
// Rule relaxations are documented inline where they deviate from defaults.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import nextConfig from "eslint-config-next";
import prettierConfig from "eslint-config-prettier";

export default tseslint.config(
  // ---- Global ignores -------------------------------------------------------
  {
    ignores: [
      "node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "**/out/**",
      "**/.sst/**",
      ".sst/**",
      ".ssc/**",
      "**/pnpm-lock.yaml",
      "pnpm-lock.yaml",
      // Legacy Python pipeline — kept for reference, not linted.
      "AI-Newsletter-Pipeline-main - OLD - DO NOT USE/**",
      // Generated by Next.js tooling.
      "**/next-env.d.ts",
      "**/*.tsbuildinfo",
    ],
  },

  // ---- Base JS recommended --------------------------------------------------
  js.configs.recommended,

  // ---- typescript-eslint recommended (repo-wide, TS/TSX only) ---------------
  ...tseslint.configs.recommended,

  // ---- Per-package rule overrides -------------------------------------------
  {
    files: ["**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}"],
    rules: {
      // Use the TS-aware version so types-only imports aren't flagged.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  // ---- Next.js config, scoped to web/ ---------------------------------------
  // eslint-config-next v16 ships an array of flat config objects. We scope
  // every entry to web/** so worker/shared (Node tsx) aren't held to Next's
  // React/browser rules.
  ...nextConfig.map((entry) => ({
    ...entry,
    files: ["web/**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    // Next's config turns several useful rules off or to "warn" for DX; we keep
    // the framework's defaults but re-enable TS unused-vars (defined above) is
    // intentionally NOT overridden here — Next's set runs first, then our
    // global TS block re-applies the rule above. To keep precedence simple we
    // only relax naming here:
    rules: {
      ...entry.rules,
      // Relaxation: this app uses the Next.js App Router only — there is no
      // `pages/` directory. The rule's settings processor prints a noisy
      // "Pages directory cannot be found" warning on every run otherwise, and
      // the rule has nothing to check against. Turned off repo-wide for web.
      "jsx-a11y/anchor-is-valid": "off",
      // The above is a no-op for App Router; the real silencer is configuring
      // the rule below. We disable it because it targets the Pages Router.
      "jsx-a11y/no-html-link-for-pages": "off",
    },
  })),

  // ---- Prettier must be LAST -----------------------------------------------
  // Turns OFF all ESLint rules that conflict with Prettier formatting.
  prettierConfig,
);
